name: 'NoMore Spam'
description: 'Automatically detect and close spam issues and PRs using AI'
author: 'JohnsonRan'
branding:
  icon: 'shield'
  color: 'red'

inputs:
  github-token:
    description: 'GitHub token with issues:write, pull-requests:write, contents:read, and models:read permissions'
    required: true
    default: ${{ github.token }}
  ai-model:
    description: 'AI model to use for spam detection'
    required: false
    default: 'openai/gpt-4o'
  ai-base-url:
    description: 'Custom AI API base URL (OpenAI compatible). If not provided, GitHub Models API will be used'
    required: false
    default: ''
  ai-api-key:
    description: 'Custom AI API key. If not provided, GitHub token will be used'
    required: false
    default: ''
  labels:
    description: 'Comma-separated list of labels for AI to classify issues (e.g., "bug,enhancement,question"). Note: "question" label is automatically added to unclear issues'
    required: false
    default: 'bug,enhancement,question'
  analyze-file-changes:
    description: 'Whether to analyze PR file changes for spam detection (true/false)'
    required: false
    default: 'true'
  max-analysis-depth:
    description: 'Analysis depth: light=3 files/3 lines, normal=5 files/5 lines, deep=10 files/10 lines'
    required: false
    default: 'normal'
  blacklist:
    description: 'Comma-separated list of GitHub usernames to be automatically closed without AI analysis (e.g., "spammer1,spammer2")'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm ci --production
        
    - name: Run NoMore Spam
      shell: bash
      run: |
        cd ${{ github.action_path }}
        node src/index.js
      env:
        INPUT_GITHUB-TOKEN: ${{ inputs.github-token }}
        INPUT_AI-MODEL: ${{ inputs.ai-model }}
        INPUT_LABELS: ${{ inputs.labels }}
        INPUT_ANALYZE-FILE-CHANGES: ${{ inputs.analyze-file-changes }}
        INPUT_MAX-ANALYSIS-DEPTH: ${{ inputs.max-analysis-depth }}
        INPUT_BLACKLIST: ${{ inputs.blacklist }}
        INPUT_AI-BASE-URL: ${{ inputs.ai-base-url }}
        INPUT_AI-API-KEY: ${{ inputs.ai-api-key }}
